export const REQUEST_ALLPOSTED_JOBS="REQUEST_ALLPOSTED_JOBS";
export const REQUEST_ALLPOSTED_JOBS_SUCCESS="REQUEST_ALLPOSTED_JOBS_SUCCESS";
export const REQUEST_ALLPOSTED_JOBS_FAILURE="REQUEST_ALLPOSTED_JOBS_FAILURE";


export const REQUEST_POST_JOB="REQUEST_POST_JOB";
export const REQUEST_POST_JOB_SUCCESS="REQUEST_POST_JOB_SUCCESS";
export const REQUEST_POST_JOB_FAILURE="REQUEST_POST_JOB_FAILURE";
